M48
; DRILL file {KiCad 8.0.4} date 2024-09-07T15:06:05-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-07T15:06:05-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1276
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1770
%
G90
G05
T1
X3.214Y-1.444
X4.02Y-2.564
X5.766Y-2.36
X6.019Y-4.016
T2
X3.597Y-0.932
X5.717Y-0.932
M30
